version: '2.4'

services:
  s3:
    image: minio/minio:latest
#    ports:
#      - "9000:9000"
#      - "9099:9099"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - storage-minio:/Users/vassil/projects/uebung_minio/data
#    command: server --address ":9099" --console-address ":9000" /data
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    ports:
        # Bind explicitly to 127.0.0.1
        - "127.0.0.1:9000:9000"
        - "9001:9001"
    restart: "unless-stopped"

volumes:
 storage-minio:
#    volumes:
#        - s3data:/data
